### ISSUE TITLE
Change software development process

### ISSUE THREAD

**Issue by JanStaschulat** [micro-ROS/rclc#75]
Change software development process in micro-ros/rclc repository.

**Prolem:**
- [ros2/rclc](https://github.com/ros2/rclc) and [micro-ros/rclc](https://github.com/micro-ROS/rclc) repositories have to be kept in-sync. 
- issues can be created on ros2 as well as micro-ros repo
- duplicate merge of micro-ros features branches 
   - first from `micro-ros/rclc:feature-branch` to `micro-ros/rclc:master` and, 
   - secondly, from `micro-ros/rclc:master` to `ros2/rclc:master`
- creation of bloom release from `ros2/rclc` involves bumping version, this change needs to be pulled back to `micro-ros/rclc`fork.

**New software development process:**
- the `micro-ros/rclc:master` branch will be deleted
- new feature branches in `micro-ros/rclc` repository shall be created from `ros2/rclc:master` 
- pull requests shall be created to `ros2/rclc:master`

**Benefits:**
- no synchronization necessary between [ros2/rclc](https://github.com/ros2/rclc) and [micro-ros/rclc](https://github.com/micro-ROS/rclc) repositories 
- single location for issues
- continue development of new features in [micro-ros/rclc](https://github.com/micro-ROS/rclc) repository

**TODO:**

- [x] resolve all errors due to bloom releases on ros2/rclc
- [x] close or transfer all open issues to ros2/rclc:issues
- [x] keep all feature branches at micro-ros/rclc => they need to be re-based to ros2/rclc later
- [x] merge or close all open pull requests on micro-ros/rclc 
- [x] make a pull from ros2/rclc to micro-ros/rclc
- [x] update scripts in micro-ros repositories : replace miro-ros/rclc:master to ros2/rclc:master (Pablo)
- [x] rename `micro-ros/rclc:master` to `micro-ros/rclc:master-depricated`
- [x] change default branch to  `micro-ros/rclc:main`
- [x] delete `micro-ros/rclc:master-depricated`
- [x] inform community (presented in embedded working group on 03/03/2021)

**Comment by JanStaschulat** [comment]
@pablogs9 
Could you check if that works and give me feedback?
- [ ] update scripts in micro-ros repositories : replace `miro-ros/rclc:master` with `ros2/rclc:master`

**Comment by JanStaschulat** [comment]
Merged all open pull requests from micro-ros/rclc to ros2/rclc
- https://github.com/ros2/rclc/pull/44
- https://github.com/ros2/rclc/pull/45
- https://github.com/ros2/rclc/pull/46
- https://github.com/ros2/rclc/pull/53

**Comment by JanStaschulat** [comment]
PRs that change `micro-ros/rclc` to `ros2/rclc`:
- [x] https://github.com/micro-ROS/micro_ros_setup/pull/273
- [x] https://github.com/micro-ROS/micro-ROS.github.io/pull/282
- [x] https://github.com/micro-ROS/micro_ros_espidf_component/pull/40
- [x] https://github.com/micro-ROS/micro_ros_mbed/pull/1
- [x] https://github.com/micro-ROS/micro_ros_zephyr_module/pull/15

**Comment by pablogs9** [comment]
PRs that change `micro-ros/rclc` to `ros2/rclc`: All merged.

At this point micro-ROS build system should not be using `micro-ros/rclc`

**Comment by JanStaschulat** [comment]
@norro @ralph-lange @pablogs9 I changed default branch from `master` to `main` and renamed `master` to `master-depricated` in micro-ros/rclc. If everything works fine, I'll delete this branch. (03.03.2021: update: I deleted the `master-depricated` branch.)

Please update the name of the main branch of rclc-repository if necessary:
```C
git branch -m master_new main
git fetch origin
git branch -u origin/main main
```
Could you feedback, if the new setup works fine for you?

**Comment by pablogs9** [comment]
Nope, I need to change it at some points. I'll back in while.

**Comment by pablogs9** [comment]
Have you done it? I'm not seeing the `main` branch here: https://github.com/ros2/rclc/branches

**Comment by JanStaschulat** [comment]
@pablogs9. All changes were done in the micro-ros/rclc repository:
https://github.com/micro-ROS/rclc/branches

There are no changes in ros2/rclc.

**Comment by pablogs9** [comment]
Ok, so I'm not modifying anything. Thanks, Jan.

**Comment by JanStaschulat** [comment]
I reviewed your pull requests, there I only saw that you replaced `micro-ros/rclc` by `ros2/rclc` so not identifying the `master` branch. So I think it should be fine. 

Could you test, if all the repositories, in which you had to make this change, are up-and-running again, aka `colcon build` and `colcon test` run successfully?

**Comment by pablogs9** [comment]
They have passed CI correctly. There are a couple of external components (IDF, Zephyr and mbed) that use the master branch from ` ros2/rclc` so if at some moment you change it we should update them.

**Comment by JanStaschulat** [comment]
Thanks for the feedback. We will not change the master branch of `ros2/rclc`.

**Comment by JanStaschulat** [comment]
Deleted `master-depricated` branch.
